Use HotelManager;
GO

CREATE PROCEDURE [dbo].[sp_GetAllRoomWithDate]

AS
	SELECT RoomID, RoomName, (SELECT TOP 1 ORDERDETAIL.StartDate FROM ORDERDETAIL WHERE ORDERDETAIL.RoomID=ROOM.RoomID ORDER BY ORDERDETAIL.StartDate) AS StartDate, (SELECT TOP 1 ORDERDETAIL.EndDate FROM ORDERDETAIL WHERE ORDERDETAIL.RoomID=ROOM.RoomID ORDER BY ORDERDETAIL.StartDate) AS EndDate, ROOM.RoomTypeID, ROOMTYPE.RoomTypeName, NumberOfBeds, Description, ROOM.StatusID, STATUS.StatusName
	FROM ROOM, ROOMTYPE, STATUS WHERE ROOM.RoomTypeID=ROOMTYPE.RoomTypeID AND ROOM.StatusID = STATUS.StatusID

GO
